add field is_complete in model Task
kshevchuk17/TestTaskForBotConversa pull request #8
Opened 2021-05-23 12:39 UTC by kshevchuk17

2021-05-23 13:02 UTC, kshevchuk17 commented
я тут случайно другие изменения закоментил но они не критичны)

2021-05-24 09:37 UTC, ilyaborodin requested changes

2021-05-24 09:37 UTC, ilyaborodin commented on src/trello/admin.py
> +	list_filter = ('due_date', 'created_at', 'is_complete')
В каком кейсе это будет применяться? по мне так юзелес. Я бы сделал в админке только проекты и юзеров

2021-05-24 09:37 UTC, ilyaborodin commented on src/trello/views/project_view.py
> +class ProjectAddManagerView(generics.UpdateAPIView):
Почему назвается AddManagerView. хотя тут можно поболее сделать, чнм просто манагеров добавить. И вообще ты не тестировал этот эндпоинт, ибо как будет работать на фронте это, откуда фронт будет брать ид юзеров?

2021-05-24 09:37 UTC, ilyaborodin commented on src/trello/views/project_view.py
>  		return Project.objects.filter(id=project)
уххх, дичь какая. Зачем это, ты по id должен к элементу обращаться

2021-05-24 09:41 UTC, kshevchuk17 commented on src/trello/views/project_view.py
>  		return Project.objects.filter(id=project)
эта вьюха недоделана, я ее случайно закомитил и вот сейчас читаю твою ссанину про эту ссанину)
вмерж я исправлю потом

2021-05-24 09:48 UTC, merged